[project]
protostar-version = "0.8.1"
lib-path = "lib"
cairo-path = ["lib", "lib/cairo_contracts_git/src", "lib/realms_contracts_git", "lib/argent_contracts_starknet_git"]    # build, test

[contracts]
main = ["contracts/mercenary.cairo"]

[test]
target = ["tests"]